project.type="custom"
project.version_file="src/lib/system.sh"
project.version_pattern="version[[:space:]]*=[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+)"
project.title="giv"
project.description="cli tool"
project.url="giv is a CLI utility for generating changelogs and summaries."
api.url="http://localhost:11434/v1/chat/completions"
api.model="devstral"
api.key="ollama"
initialized="true"
